include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [ ios/**, android/**, test/** ]
  plugins:
    - dart_code_metrics

  errors:
    empty_constructor_bodies: error
    missing_required_param: error
    always_use_package_imports: error
    avoid_types_as_parameter_names: error
    close_sinks: error
    unnecessary_statements: warning
    non_constant_identifier_names: warning
    file_names: error

linter:
  rules:
    camel_case_types: true
    avoid_empty_else: true
    constant_identifier_names: false
    use_key_in_widget_constructors: false
    avoid_print: true
    always_use_package_imports: false
    avoid_returning_null_for_future: true
    avoid_types_as_parameter_names: true
    no_duplicate_case_values: true
    throw_in_finally: true
    unnecessary_statements: true
    valid_regexps: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    always_specify_types: true
    annotate_overrides: true
    empty_constructor_bodies: true
    empty_catches: true
    file_names: true
    lines_longer_than_80_chars: true
    no_default_cases: true
    prefer_conditional_assignment: true
    prefer_double_quotes: false
    prefer_mixin: true

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 8
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
    - ios/**
    - android/**
  rules:
    newline-before-return:
      severity: style
    no-boolean-literal-compare:
      severity: warning
    no-empty-block:
      severity: error
    prefer-conditional-expressions:
      severity: warning
    no-magic-number:
      severity: style
      allowed: [ 0,1,2,3,4,5,6,7,8,9 ]
      avoid-unused-parameters:
        severity: warning

#   severity -> none, style, performance, warning, error.